<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 3.5.8 setup script
 * Date: Fri, 26 Apr 2013 10:08:35 -0700
 */

/* Servers configuration */
$i = 0;

/* Server: Travel Application [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'Travel Application';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';

/* End of servers configuration */

$cfg['blowfish_secret'] = '517ab2bb937c54.81838610';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>